export const referenceDataMetadata = {
  checkedOn: "2026-08-07",
  geographyEdition: "ZamStats 2022 Census summary, published/revised 2024",
  geographySource:
    "https://www.zamstats.gov.zm/Publications/Revised%202022%20Census%20of%20Population%20and%20Housing%20Summary%20Report%20Volume%20II.pdf",
  geographyCrossCheck:
    "https://www.mlgrd.gov.zm/wp-content/uploads/2025/01/Environmental-and-Social-Management-Plan-ESMP-Zambia-Devolution-Support-Program.pdf",
  categoryBasis:
    "ISIC Rev. 4-informed product taxonomy, prioritised using the Zed360 discovery survey",
  categorySource: "https://pacra.org.zm/classifications",
};

export const provincesWithDistricts = [
  {
    name: "Central",
    slug: "central",
    districts: [
      "Chibombo",
      "Chisamba",
      "Chitambo",
      "Kabwe",
      "Kapiri Mposhi",
      "Luano",
      "Mkushi",
      "Mumbwa",
      "Ngabwe",
      "Serenje",
      "Shibuyunji",
    ],
  },
  {
    name: "Copperbelt",
    slug: "copperbelt",
    districts: [
      "Chililabombwe",
      "Chingola",
      "Kalulushi",
      "Kitwe",
      "Luanshya",
      "Lufwanyama",
      "Masaiti",
      "Mpongwe",
      "Mufulira",
      "Ndola",
    ],
  },
  {
    name: "Eastern",
    slug: "eastern",
    districts: [
      "Chadiza",
      "Chama",
      "Chasefu",
      "Chipangali",
      "Chipata",
      "Kasenengwa",
      "Katete",
      "Lumezi",
      "Lundazi",
      "Lusangazi",
      "Mambwe",
      "Nyimba",
      "Petauke",
      "Sinda",
      "Vubwi",
    ],
  },
  {
    name: "Luapula",
    slug: "luapula",
    districts: [
      "Chembe",
      "Chienge",
      "Chifunabuli",
      "Chipili",
      "Kawambwa",
      "Lunga",
      "Mansa",
      "Milenge",
      "Mwansabombwe",
      "Mwense",
      "Nchelenge",
      "Samfya",
    ],
  },
  {
    name: "Lusaka",
    slug: "lusaka",
    districts: ["Chilanga", "Chongwe", "Kafue", "Luangwa", "Lusaka", "Rufunsa"],
  },
  {
    name: "Muchinga",
    slug: "muchinga",
    districts: [
      "Chinsali",
      "Isoka",
      "Kanchibiya",
      "Lavushimanda",
      "Mafinga",
      "Mpika",
      "Nakonde",
      "Shiwang'andu",
    ],
  },
  {
    name: "Northern",
    slug: "northern",
    districts: [
      "Chilubi",
      "Kaputa",
      "Kasama",
      "Lunte",
      "Lupososhi",
      "Luwingu",
      "Mbala",
      "Mporokoso",
      "Mpulungu",
      "Mungwi",
      "Nsama",
      "Senga Hill",
    ],
  },
  {
    name: "North-Western",
    slug: "north-western",
    districts: [
      "Chavuma",
      "Ikelenge",
      "Kabompo",
      "Kalumbila",
      "Kasempa",
      "Manyinga",
      "Mufumbwe",
      "Mushindamo",
      "Mwinilunga",
      "Solwezi",
      "Zambezi",
    ],
  },
  {
    name: "Southern",
    slug: "southern",
    districts: [
      "Chikankata",
      "Chirundu",
      "Choma",
      "Gwembe",
      "Itezhi-Tezhi",
      "Kalomo",
      "Kazungula",
      "Livingstone",
      "Mazabuka",
      "Monze",
      "Namwala",
      "Pemba",
      "Siavonga",
      "Sinazongwe",
      "Zimba",
    ],
  },
  {
    name: "Western",
    slug: "western",
    districts: [
      "Kalabo",
      "Kaoma",
      "Limulunga",
      "Luampa",
      "Lukulu",
      "Mitete",
      "Mongu",
      "Mulobezi",
      "Mwandi",
      "Nalolo",
      "Nkeyema",
      "Senanga",
      "Sesheke",
      "Shang'ombo",
      "Sikongo",
      "Sioma",
    ],
  },
];

export const categories = [
  ["Agriculture & Farming", "agriculture-farming"],
  ["Mining, Energy & Utilities", "mining-energy-utilities"],
  ["Manufacturing & Industrial", "manufacturing-industrial"],
  ["Construction & Home Services", "construction-home-services"],
  ["Retail & Shopping", "retail-shopping"],
  ["Automotive & Transport", "automotive-transport"],
  ["Accommodation & Travel", "accommodation-travel"],
  ["Food & Hospitality", "food-hospitality"],
  ["Technology & Electronics", "technology-electronics"],
  ["Financial & Professional Services", "financial-professional-services"],
  ["Property & Real Estate", "property-real-estate"],
  ["Education & Training", "education-training"],
  ["Health & Wellness", "health-wellness"],
  ["Beauty & Personal Care", "beauty-personal-care"],
  ["Events, Media & Entertainment", "events-media-entertainment"],
  ["Community & Other Services", "community-other-services"],
].map(([name, slug], index) => ({
  name,
  slug,
  parentSlug: null,
  sortOrder: index + 1,
}));

export const launchSubcategories = [
  ["Accommodation", "accommodation", "accommodation-travel"],
  ["Travel & Tours", "travel-tours", "accommodation-travel"],
  ["Hair Salons & Barbers", "hair-salons-barbers", "beauty-personal-care"],
  ["Cosmetics & Perfumes", "cosmetics-perfumes", "beauty-personal-care"],
  ["Electronics", "electronics", "technology-electronics"],
  ["IT Services", "it-services", "technology-electronics"],
  ["Building Materials", "building-materials", "construction-home-services"],
  ["Contractors & Trades", "contractors-trades", "construction-home-services"],
  ["Photography & Video", "photography-video", "events-media-entertainment"],
  ["Restaurants & Catering", "restaurants-catering", "food-hospitality"],
  ["Fashion & Clothing", "fashion-clothing", "retail-shopping"],
].map(([name, slug, parentSlug], index) => ({
  name,
  slug,
  parentSlug,
  sortOrder: index + 1,
}));

export function toSlug(value) {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/['’]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}
